# Generated by Django 5.2.8 on 2025-12-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
    ]
